version: "3.8"
services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: Dockerfile
    tty: true
    environment:
      - WATCHPACK_POLLING=true

    # Set envrionment variables based on the .env file
    env_file:
      - ./next-app/.env.local

    volumes:
      - ./next-app:/app
      - ./next-app/node_modules:/app/node_modules:delegated
      - next_cache_volume:/app/.next
      - build_volume:/app/build:nocopy
    ports:
      - 3000:3000
    restart: always
    networks:
      - default

volumes:
  next_cache_volume:
  build_volume:
